AWSTemplateFormatVersion: "2010-09-09"
Description: "One S3 bucket to store invoice pdf files"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: invoices3bucket
      AccessControl: Private