---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a VPC, subnet, IGW, security group, and EC2 instance with Apache

Resources:
  mywebVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: mywebVPC

  publicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref mywebVPC
      AvailabilityZone: us-west-2c
      Tags:
        - Key: Name
          Value: PublicSubnet

  internetGateway:
    Type: AWS::EC2::InternetGateway

  attachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref mywebVPC
      InternetGatewayId: !Ref internetGateway

  routeTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref mywebVPC

  route:
    Type: AWS::EC2::Route
    DependsOn: attachGateway
    Properties:
      RouteTableId: !Ref routeTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref internetGateway

  subnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref publicSubnet
      RouteTableId: !Ref routeTable

  mywebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  SLWebapp1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-074be47313f84fa38"  # Replace with the correct AMI for your region
      InstanceType: t2.micro
      KeyName: OregonKP
      SecurityGroups:
        - Ref: mywebSG
      SubnetId: !Ref publicSubnet 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          cat <<EOF > /var/www/html/index.html
          <html>
          <head>
          <style>
          body {
              background-color: black;
              color: yellow;
          }
          </style>
          </head>
          <body>
          <h1>Here is my website</h1>
          </body>
          </html>
          EOF
          systemctl start httpd
          systemctl enable httpd

